// Title:        IntlRateResponse
// Copyright:    Copyright (c) 2002
// Author:       XML-Schema Compiler
// Company:      Adaptinet, Inc.
// Description:  This class was generated by Adaptinet's XML-Schema Compiler
// Schema name:  C:\projects\storefront\webuspsrate\webuspsrate.xsd
// Java SDK:     1.2.2 or later

package com.storefront.webuspsrate;
import java.io.Serializable;

import java.util.*;

public class IntlRateResponse implements Serializable  {
	public Iterator getPackageIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_Package==null) return false;
				if(last<0) {
					last = _Package.length;
					while(--last>-1&&_Package[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _Package[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_Package[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Package getPackage(int idx) { 
		return (Package)_Package[idx];
	}
	public void setPackage(Package newValue) { 
		if(_Package!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_Package.length;__I_A++) {
				if(_Package[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_Package.length;
				Package array[] = new Package[__OPEN_A+10];
				System.arraycopy(_Package,0,array,0,_Package.length);
				_Package = array;
			}
			_Package[__OPEN_A] = newValue;
		}
		else {
			_Package = new Package[10];
			_Package[0] = newValue;
		}
	}
	private Package _Package[] = null;
}

