// Title:        Package
// Copyright:    Copyright (c) 2002
// Author:       XML-Schema Compiler
// Company:      Adaptinet, Inc.
// Description:  This class was generated by Adaptinet's XML-Schema Compiler
// Schema name:  C:\projects\storefront\webuspsrate\webuspsrate.xsd
// Java SDK:     1.2.2 or later

package com.storefront.webuspsrate;
import java.io.Serializable;

import java.util.*;

public class Package implements Serializable  {
	public Pounds getPounds() { 
		return _Pounds;
	}
	public void setPounds(Pounds newValue) { 
		_Pounds = newValue;
	}
	public Ounces getOunces() { 
		return _Ounces;
	}
	public void setOunces(Ounces newValue) { 
		_Ounces = newValue;
	}
	public MailType getMailType() { 
		return _MailType;
	}
	public void setMailType(MailType newValue) { 
		_MailType = newValue;
	}
	public Country getCountry() { 
		return _Country;
	}
	public void setCountry(Country newValue) { 
		_Country = newValue;
	}
	public Prohibitions getProhibitions() { 
		return _Prohibitions;
	}
	public void setProhibitions(Prohibitions newValue) { 
		_Prohibitions = newValue;
	}
	public Restrictions getRestrictions() { 
		return _Restrictions;
	}
	public void setRestrictions(Restrictions newValue) { 
		_Restrictions = newValue;
	}
	public Observations getObservations() { 
		return _Observations;
	}
	public void setObservations(Observations newValue) { 
		_Observations = newValue;
	}
	public CustomsForms getCustomsForms() { 
		return _CustomsForms;
	}
	public void setCustomsForms(CustomsForms newValue) { 
		_CustomsForms = newValue;
	}
	public ExpressMail getExpressMail() { 
		return _ExpressMail;
	}
	public void setExpressMail(ExpressMail newValue) { 
		_ExpressMail = newValue;
	}
	public AreasServed getAreasServed() { 
		return _AreasServed;
	}
	public void setAreasServed(AreasServed newValue) { 
		_AreasServed = newValue;
	}
	public Iterator getServiceIterator() { 
		return new Iterator() {
			int cursor=0;
			int last=-1;
			public boolean hasNext() {
				if(_Service==null) return false;
				if(last<0) {
					last = _Service.length;
					while(--last>-1&&_Service[last]==null);
					last++;
				}
				return cursor!=last;
			}
			public Object next() {
				try {
					return _Service[cursor++];
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
			public void remove() {
				try {
					_Service[cursor++]=null;
				} catch(IndexOutOfBoundsException e) {
					throw new NoSuchElementException();
				}
			}
		};
	}
	public Service getService(int idx) { 
		return (Service)_Service[idx];
	}
	public void setService(Service newValue) { 
		if(_Service!=null) {
			int __OPEN_A=-1;
			for(int __I_A=0;__I_A<_Service.length;__I_A++) {
				if(_Service[__I_A]==null) {
					__OPEN_A=__I_A;
					break;
				}
			}
			if(__OPEN_A<0) {
				__OPEN_A=_Service.length;
				Service array[] = new Service[__OPEN_A+10];
				System.arraycopy(_Service,0,array,0,_Service.length);
				_Service = array;
			}
			_Service[__OPEN_A] = newValue;
		}
		else {
			_Service = new Service[10];
			_Service[0] = newValue;
		}
	}
	public String getID() {
		if(_ID!=null) {
			return new String(_ID);
		}
		else {
			return null;
		}
	}
	public void setID(String newValue) {
		_ID = newValue!=null ? newValue.toCharArray() : null;
	}
	private Pounds _Pounds = null;
	private Ounces _Ounces = null;
	private MailType _MailType = null;
	private Country _Country = null;
	private Prohibitions _Prohibitions = null;
	private Restrictions _Restrictions = null;
	private Observations _Observations = null;
	private CustomsForms _CustomsForms = null;
	private ExpressMail _ExpressMail = null;
	private AreasServed _AreasServed = null;
	private Service _Service[] = null;
	private char[] _ID;
}

