// Title:        Service
// Copyright:    Copyright (c) 2002
// Author:       XML-Schema Compiler
// Company:      Adaptinet, Inc.
// Description:  This class was generated by Adaptinet's XML-Schema Compiler
// Schema name:  C:\projects\storefront\webuspsrate\webuspsrate.xsd
// Java SDK:     1.2.2 or later

package com.storefront.webuspsrate;
import java.io.Serializable;

import java.util.*;

public class Service implements Serializable  {
	public String getContentData() {
		return _contentData;
	}
	public void setContentData(String newValue) {
		 _contentData = newValue;
	}
	public Pounds getPounds() { 
		return _Pounds;
	}
	public void setPounds(Pounds newValue) { 
		_Pounds = newValue;
	}
	public Ounces getOunces() { 
		return _Ounces;
	}
	public void setOunces(Ounces newValue) { 
		_Ounces = newValue;
	}
	public MailType getMailType() { 
		return _MailType;
	}
	public void setMailType(MailType newValue) { 
		_MailType = newValue;
	}
	public Country getCountry() { 
		return _Country;
	}
	public void setCountry(Country newValue) { 
		_Country = newValue;
	}
	public Postage getPostage() { 
		return _Postage;
	}
	public void setPostage(Postage newValue) { 
		_Postage = newValue;
	}
	public SvcCommitments getSvcCommitments() { 
		return _SvcCommitments;
	}
	public void setSvcCommitments(SvcCommitments newValue) { 
		_SvcCommitments = newValue;
	}
	public SvcDescription getSvcDescription() { 
		return _SvcDescription;
	}
	public void setSvcDescription(SvcDescription newValue) { 
		_SvcDescription = newValue;
	}
	public MaxDimensions getMaxDimensions() { 
		return _MaxDimensions;
	}
	public void setMaxDimensions(MaxDimensions newValue) { 
		_MaxDimensions = newValue;
	}
	public MaxWeight getMaxWeight() { 
		return _MaxWeight;
	}
	public void setMaxWeight(MaxWeight newValue) { 
		_MaxWeight = newValue;
	}
	public String getID() {
		if(_ID!=null) {
			return new String(_ID);
		}
		else {
			return null;
		}
	}
	public void setID(String newValue) {
		_ID = newValue!=null ? newValue.toCharArray() : null;
	}
	private Pounds _Pounds = new Pounds();
	private Ounces _Ounces = new Ounces();
	private MailType _MailType = new MailType();
	private Country _Country = new Country();
	private Postage _Postage = new Postage();
	private SvcCommitments _SvcCommitments = new SvcCommitments();
	private SvcDescription _SvcDescription = new SvcDescription();
	private MaxDimensions _MaxDimensions = new MaxDimensions();
	private MaxWeight _MaxWeight = new MaxWeight();
	private char[] _ID;
	private String _contentData;
}

