# Connection: idata
# Host: idata-appserver
# Saved: 2004-04-23 13:03:00
# 
insert into emaildata (name, textdata,fieldname) values ('order','<HTML><HEAD><LINK href="http://67.80.184.158:8082/StoreFrontClient/storefront.css" rel="STYLESHEET"></LINK></HEAD>',''),
    ('order','<BODY leftMargin="0" topMargin="0" onload="" marginwidth="0" marginheight="0">',''),
    ('order','<table cellSpacing="0" cellPadding="0" border="0">',''),
    ('order','<tr><td vAlign="top" width="20"><IMG src="http://67.80.184.158:8082/fernknives/images/spacer.gif" border="0"></td>',''),
    ('order','<td vAlign="top"><table id="headingTable" border="0"><tr><td>',''),
    ('order','<img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="20"></td></tr></table>',''),
    ('order','<table cellSpacing="1" cellPadding="1" width="550" border="0">',''),
    ('order','<tr><td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td></tr>',''),
    ('order','<tr><td colspan="2" valign="top">Dear:  /*Anthony Graffeo*/',''),
    ('order',',</td></tr><tr><td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td></tr>',''),
    ('order','<tr><td colspan="3" valign="top">Thanks for shopping at Fern Knives. We have received your order and will ship it promptly.',''), 
    ('order','When it ships, we\'ll send you another e-mail to let you know.</td></tr><tr>',''),
    ('order','<td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td></tr>',''),
    ('order','<tr bgcolor="#eeeecc"><td colspan="5" nowrap class="producttitle">Order</td></tr><tr>',''),
    ('order','<td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="1" height="4" /></td></tr></table>',''),
    ('order','<table border="0" width="100"><tr><td nowrap align="left"><b>ID:</b></td><td align="left"> /*87*/',''),
    ('order','</td></tr><tr><td align="left"><b>Date:</b></td><td align="left"> /*04/23/2004*/',''),
    ('order','</td></tr></table><table border="0" width="550"><tr><td colspan="2">',''),
    ('order','<img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td></tr>',''),
    ('order','<tr><td valign="top"><table border="0" cellSpacing="0" cellPadding="0"><tr><td nowrap><b>Billing Address</b></td></tr>',''),
    ('order','<tr><td nowrap>','billingname'), 
    ('order','</td></tr><tr><td nowrap>','billingaddr1'),
    ('order','</td></tr><tr><td nowrap>','billingaddr2'),
    ('order','</td></tr><tr><td nowrap>','billingaddr3'),
    ('order','</td></tr><tr><td nowrap>','billingphone'),
    ('order','</td></tr><tr><td nowrap>','billingemail'), 
    ('order','</td></tr></table></td><td valign="top"><table border="0" cellSpacing="0" cellPadding="0">',''),
    ('order','<tr><td nowrap><b>Shipping Address</b></td></tr>',''),
    ('order','<tr><td nowrap>','shippingname'), 
    ('order','</td></tr><tr><td nowrap>','shippingaddr1'),
    ('order','</td></tr><tr><td nowrap>','shippingaddr2'),
    ('order','</td></tr><tr><td nowrap>','shippingaddr3'),
    ('order','</td></tr><tr><td nowrap>','shippingphone'),
    ('order','</td></tr><tr><td nowrap>','shippingemail'), 
    ('order','</td></tr></table></td><td valign="top"><table border="0" cellSpacing="0" cellPadding="0"><tr>',''),
    ('order','<td colspan="2" nowrap><b>Credit Card Used</b></td></tr>',''),
    ('order','<tr><td nowrap>Number:</td><td>','ccnumber'),
    ('order','</td></tr><tr><td nowrap>Expiration:</td><td nowrap>','ccexpdate'),
    ('order','</td></tr></table></td></tr></table><br><table cellSpacing="1" cellPadding="2" border="0" width="550">',''),
    ('order','<tr><td nowrap align="left"><b>Item</b></td><td nowrap align="right"><b>Unit Price</b></td>',''),
    ('order','<td nowrap align="center"><b>Quantity</b></td><td nowrap align="right"><b>Item Total</b></td></tr>',''),
    ('order','<tr><td colspan="4"><table border="0" cellspacing="0" cellpadding="0"><tr><td bgcolor="#c2a877">',''),
    ('order','<img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="550" height="2"></td></tr></table></td></tr>',''),
    ('order','<tr><td align="left" width="350">','itemname'),
    ('order','<br>Item number: ','isin'),
    ('order','</td><td align="right">','unitprice'),
    ('order','</td><td align="center">','qyt'),
    ('order','</td><td align="right">','itemtotal'),
    ('order','</td></tr><tr><td colspan="4"><table border="0" cellspacing="0" cellpadding="0"><tr>',''),
    ('order','<td bgcolor="#c2a877"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="550" height="1"></td></tr></table>',''),
    ('order','</td></tr><tr><td colspan="3" align="right" nowrap><b>Merchandise Total:</b></td><td align="right"><b>','totalcost'),
    ('order','</b></td></tr><tr><td colspan="1"></td><td colspan="3" align="right"><table border="0" cellspacing="0" cellpadding="0">',''),
    ('order','<tr><td bgcolor="#c2a877"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="250" height="1"></td></tr></table></td>',''),
    ('order','</tr><tr><td colspan="3" align="right" nowrap>Shipping Costs:</td><td align="right">','shippingcost'),
    ('order','</td></tr><tr><td colspan="3" align="right" nowrap>','taxdesc'),
    ('order','</td><td align="right">','taxamt'),
    ('order','</td></tr><tr><td colspan="1"></td><td colspan="3" align="right"><table border="0" cellspacing="0" cellpadding="0"><tr>',''),
    ('order','<td bgcolor="#c2a877"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="250" height="1"></td></tr></table></td></tr>',''),
    ('order','<tr><td colspan="3" align="right" nowrap><b>Amount Charged to Your Credit Card:</b></td><td align="right"><b>','total'),
    ('order','</b></td></tr><tr><td colspan="3" valign="top">If you have any questions, you can reply to this e-mail or call usbetween 9:00 AM and 7:00 PM Eastern time.',''),
    ('order','</td></tr><tr><td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td>',''),
    ('order','</tr><tr><td colspan="3" valign="top">US & Canada: 800-555-1212<br />All other countries call: (International Access Code) +973-360-0086</td></tr>',''),
    ('order','<tr><td colspan="2"><img src="http://67.80.184.158:8082/fernknives/images/spacer.gif" width="5" height="5"></td></tr>',''),
    ('order','<tr><td colspan="3" valign="top">Thanks again!</td></tr></table></td></tr></table></BODY></HTML>','');