/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=NO_AUTO_VALUE_ON_ZERO */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `storefront`;
USE `storefront`;
CREATE TABLE `countrycodes` (
  `code` char(3) NOT NULL default '',
  `name` varchar(100) default '',
  `postalcode` varchar(100) default '',
  PRIMARY KEY  (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('AD','Andorra','Andorra'),('AE','United Arab Emirates','United Arab Emirates'),('AF','Afghanistan','Afghanistan'),('AG','Antigua and Barbuda','Antigua and Barbuda'),('AI','Anguilla','Anguilla'),('AL','Albania','Albania'),('AM','Armenia','Armenia'),('AN','Netherlands Antilles','Netherlands Antilles'),('AO','Angola','Angola'),('AQ','Antarctica','Antarctica'),('AR','Argentina','Argentina'),('ARP','Old style Arpanet','Old style Arpanet'),('AS','American Samoa','American Samoa'),('AT','Austria','Austria'),('AU','Australia','Australia'),('AW','Aruba','Aruba'),('AZ','Azerbaidjan','Azerbaidjan'),('BA','Bosnia-Herzegovina','Bosnia-Herzegovina'),('BB','Barbados','Barbados'),('BD','Bangladesh','Bangladesh'),('BE','Belgium','Belgium'),('BF','Burkina Faso','Burkina Faso'),('BG','Bulgaria','Bulgaria'),('BH','Bahrain','Bahrain'),('BI','Burundi','Burundi'),('BJ','Benin','Benin'),('BM','Bermuda','Bermuda'),('BN','Brunei Darussalam','Brunei Darussalam'),('BO','Bolivia','Bolivia');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('BR','Brazil','Brazil'),('BS','Bahamas','Bahamas'),('BT','Bhutan','Bhutan'),('BV','Bouvet Island','Bouvet Island'),('BW','Botswana','Botswana'),('BY','Belarus','Belarus'),('BZ','Belize','Belize'),('CA','Canada','Canada'),('CC','Cocos (Keeling), Islands','Cocos (Keeling), Islands'),('CF','Central African Republic','Central African Republic'),('CG','Congo','Congo'),('CH','Switzerland','Switzerland'),('CI','Ivory Coast (Cote D`Ivoire),','Ivory Coast (Cote D`Ivoire),'),('CK','Cook Islands','Cook Islands'),('CL','Chile','Chile'),('CM','Cameroon','Cameroon'),('CN','China','China'),('CO','Colombia','Colombia'),('DK','Denmark','Denmark'),('DM','Dominica','Dominica'),('DO','Dominican Republic','Dominican Republic'),('DZ','Algeria','Algeria'),('EC','Ecuador','Ecuador'),('EDU','USA Educational','USA Educational'),('EE','Estonia','Estonia'),('EG','Egypt','Egypt'),('EH','Western Sahara','Western Sahara'),('ER','Eritrea','Eritrea'),('ES','Spain','Spain'),('ET','Ethiopia','Ethiopia');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('FI','Finland','Finland'),('FJ','Fiji','Fiji'),('FK','Falkland Islands','Falkland Islands'),('FM','Micronesia','Micronesia'),('FO','Faroe Islands','Faroe Islands'),('FR','France','France'),('FX','France (European Territory),','France (European Territory),'),('GA','Gabon','Gabon'),('GB','England','Great Britain and Northern Ireland'),('GD','Grenada','Grenada'),('GE','Georgia','Georgia'),('GF','French Guyana','French Guyana'),('GH','Ghana','Ghana'),('GI','Gibraltar','Gibraltar'),('GL','Greenland','Greenland'),('GM','Gambia','Gambia'),('GN','Guinea','Guinea'),('GOV','USA Government','USA Government'),('GP','Guadeloupe (French),','Guadeloupe (French),'),('GQ','Equatorial Guinea','Equatorial Guinea'),('GR','Greece','Greece'),('GS','S. Georgia & S. Sandwich Isls.','S. Georgia & S. Sandwich Isls.'),('GT','Guatemala','Guatemala'),('GU','Guam (USA),','Guam (USA),'),('GW','Guinea Bissau','Guinea Bissau'),('GY','Guyana','Guyana'),('HK','Hong Kong','Hong Kong'),('HM','Heard and McDonald Islands','Heard and McDonald Islands');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('HN','Honduras','Honduras'),('HR','Croatia','Croatia'),('HT','Haiti','Haiti'),('HU','Hungary','Hungary'),('ID','Indonesia','Indonesia'),('IE','Ireland','Ireland'),('IL','Israel','Israel'),('IN','India','India'),('INT','International','International'),('IO','British Indian Ocean Territory','British Indian Ocean Territory'),('IQ','Iraq','Iraq'),('IR','Iran','Iran'),('IS','Iceland','Iceland'),('IT','Italy','Italy'),('JM','Jamaica','Jamaica'),('JO','Jordan','Jordan'),('JP','Japan','Japan'),('KE','Kenya','Kenya'),('KG','Kyrgyzstan','Kyrgyzstan'),('KH','Cambodia','Cambodia'),('KI','Kiribati','Kiribati'),('KM','Comoros','Comoros'),('KN','Saint Kitts & Nevis Anguilla','Saint Kitts & Nevis Anguilla'),('KP','North Korea','North Korea'),('KR','South Korea','South Korea'),('KW','Kuwait','Kuwait'),('KY','Cayman Islands','Cayman Islands'),('KZ','Kazakhstan','Kazakhstan'),('LA','Laos','Laos'),('LB','Lebanon','Lebanon'),('LC','Saint Lucia','Saint Lucia'),('LI','Liechtenstein','Liechtenstein');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('LK','Sri Lanka','Sri Lanka'),('LR','Liberia','Liberia'),('LS','Lesotho','Lesotho'),('LT','Lithuania','Lithuania'),('LU','Luxembourg','Luxembourg'),('LV','Latvia','Latvia'),('LY','Libya','Libya'),('MA','Morocco','Morocco'),('MC','Monaco','Monaco'),('MD','Moldavia','Moldavia'),('MG','Madagascar','Madagascar'),('MH','Marshall Islands','Marshall Islands'),('MIL','USA Military','USA Military'),('MK','Macedonia','Macedonia'),('ML','Mali','Mali'),('MM','Myanmar','Myanmar'),('MN','Mongolia','Mongolia'),('MO','Macau','Macau'),('MP','Northern Mariana Islands','Northern Mariana Islands'),('MQ','Martinique (French),','Martinique (French),'),('MR','Mauritania','Mauritania'),('MS','Montserrat','Montserrat'),('MT','Malta','Malta'),('MU','Mauritius','Mauritius'),('MV','Maldives','Maldives'),('MW','Malawi','Malawi'),('MX','Mexico','Mexico'),('MY','Malaysia','Malaysia'),('MZ','Mozambique','Mozambique'),('NA','Namibia','Namibia'),('NC','New Caledonia (French),','New Caledonia (French),'),('NE','Niger','Niger');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('NET','Network','Network'),('NF','Norfolk Island','Norfolk Island'),('NG','Nigeria','Nigeria'),('NI','Nicaragua','Nicaragua'),('NL','Netherlands','Netherlands'),('NO','Norway','Norway'),('NP','Nepal','Nepal'),('NR','Nauru','Nauru'),('NT','Neutral Zone','Neutral Zone'),('NU','Niue','Niue'),('NZ','New Zealand','New Zealand'),('OM','Oman','Oman'),('ORG','Non-Profit Making Organisations (sic),','Non-Profit Making Organisations (sic),'),('PA','Panama','Panama'),('PE','Peru','Peru'),('PF','Polynesia (French),','Polynesia (French),'),('PG','Papua New Guinea','Papua New Guinea'),('PH','Philippines','Philippines'),('PK','Pakistan','Pakistan'),('PL','Poland','Poland'),('PM','Saint Pierre and Miquelon','Saint Pierre and Miquelon'),('PN','Pitcairn Island','Pitcairn Island'),('PR','Puerto Rico','Puerto Rico'),('PT','Portugal','Portugal'),('PW','Palau','Palau'),('PY','Paraguay','Paraguay'),('QA','Qatar','Qatar'),('RE','Reunion (French),','Reunion (French),'),('RO','Romania','Romania');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('RU','Russian Federation','Russian Federation'),('RW','Rwanda','Rwanda'),('SA','Saudi Arabia','Saudi Arabia'),('SB','Solomon Islands','Solomon Islands'),('SC','Seychelles','Seychelles'),('SD','Sudan','Sudan'),('SE','Sweden','Sweden'),('SG','Singapore','Singapore'),('SH','Saint Helena','Saint Helena'),('SI','Slovenia','Slovenia'),('SJ','Svalbard and Jan Mayen Islands','Svalbard and Jan Mayen Islands'),('SK','Slovak Republic','Slovak Republic'),('SL','Sierra Leone','Sierra Leone'),('SM','San Marino','San Marino'),('SN','Senegal','Senegal'),('SO','Somalia','Somalia'),('SR','Suriname','Suriname'),('ST','Saint Tome (Sao Tome), and Principe','Saint Tome (Sao Tome), and Principe'),('SU','Former USSR','Former USSR'),('SV','El Salvador','El Salvador'),('SY','Syria','Syria'),('SZ','Swaziland','Swaziland'),('TC','Turks and Caicos Islands','Turks and Caicos Islands'),('TD','Chad','Chad'),('TF','French Southern Territories','French Southern Territories'),('TG','Togo','Togo');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('TH','Thailand','Thailand'),('TJ','Tadjikistan','Tadjikistan'),('TK','Tokelau','Tokelau'),('TM','Turkmenistan','Turkmenistan'),('TN','Tunisia','Tunisia'),('TO','Tonga','Tonga'),('TP','East Timor','East Timor'),('TR','Turkey','Turkey'),('TT','Trinidad and Tobago','Trinidad and Tobago'),('TV','Tuvalu','Tuvalu'),('TW','Taiwan','Taiwan'),('TZ','Tanzania','Tanzania'),('UA','Ukraine','Ukraine'),('UG','Uganda','Uganda'),('UM','USA Minor Outlying Islands','USA Minor Outlying Islands'),('US','United States','United States'),('UY','Uruguay','Uruguay'),('UZ','Uzbekistan','Uzbekistan'),('VA','Vatican City State','Vatican City State'),('VC','Saint Vincent & Grenadines','Saint Vincent & Grenadines'),('VE','Venezuela','Venezuela'),('VG','Virgin Islands (British),','Virgin Islands (British),'),('VI','Virgin Islands (USA),','Virgin Islands (USA),'),('VN','Vietnam','Vietnam'),('VU','Vanuatu','Vanuatu'),('WF','Wallis and Futuna Islands','Wallis and Futuna Islands'),('WS','Samoa','Samoa');
INSERT INTO `countrycodes` (`code`,`name`,`postalcode`) VALUES ('YE','Yemen','Yemen'),('YT','Mayotte','Mayotte'),('YU','Yugoslavia','Yugoslavia'),('ZA','South Africa','South Africa'),('ZM','Zambia','Zambia'),('ZR','Zaire','Zaire'),('ZW','Zimbabwe','Zimbabwe');
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
